### ISSUE TITLE
Instructions on experiment reproduction

### ISSUE THREAD

**Issue by thangld201** [CuteyThyme/Q-Diversity#1]
Hi, thanks for the great works !

I'm trying to re-run the experiments in the papers (including those with the baselines), but I'm currently a bit lost at the project's structure. Do you have any instruction files (*.sh scripts, for example) that help in conducting experiments in the papers ? @CuteyThyme

**Comment by CuteyThyme** [comment]
Of course, thank you for reminding me of the update of this repository. I will reorganize the datasets and corresponding instruction files recently.
